language: ruby
rvm:
  - 2.3.0
env:
  - DB=postgresql
addons:
  postgresql: "9.4"
cache: bundler
script:
  - bundle exec rake db:schema:load RACK_ENV=test
  - xvfb-run -a bundle exec rspec
before_script:
  - psql -c 'create database hola_api_travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - RACK_ENV=test bundle exec rake db:migrate
