language: ruby
rvm:
  - 2.3.0
env:
  - DB=postgresql
addons:
  postgresql: "9.4"
cache: bundler
#before_script:
#  - psql -c 'create database qna_travis_ci_test;' -U postgres
#  - cp config/database.yml.travis config/database.yml
#  - RAILS_ENV=test bundle exec rake db:migrate
#script:
#  - RAILS_ENV=test bundle exec rspec spec/
script:
  - bundle exec rake db:schema:load RACK_ENV=test
  # - xvfb-run -a bundle exec rspec
before_script:
  - psql -c 'create database hola_api_travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  # - cp config/private_pub.yml.travis config/private_pub.yml
  - RACK_ENV=test bundle exec rake db:migrate
  # - bundle exec rackup private_pub.ru -s thin -E production &
  # - sleep 3
